stages:
  - test
  - analysis
  - docker
  - deploy

cache:
  paths:
    - vendor/

composer:
  image: $BUILDIMAGE
  cache:
    paths:
      - vendor/
  script:
    - php --version
    - cp .env.example .env
    - time composer install --no-progress
  artifacts:
    expire_in: 1 hour
    paths:
      - vendor/

test:
  image: $BUILDIMAGE
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  script:
    - cp -n .env.example .env
    - npm ci --prefer-offline --no-audit --progress=false --no-fund
    - npm run build
    - php artisan key:generate
    - XDEBUG_MODE=coverage php artisan test --parallel --coverage-text --log-junit junit-report.xml --coverage-cobertura cobertura-report.xml
  needs:
    - composer
  artifacts:
    when: always
    expire_in: 1month
    paths:
      - build
      - coverage
      - clover.xml
    reports:
      junit: junit-report.xml
      coverage_report:
        coverage_format: cobertura
        path: cobertura-report.xml

security-check-composer:
  image: $BUILDIMAGE
  stage: analysis
  needs:
    - composer
  variables:
    GIT_DEPTH: 1
  script:
    - COMPOSER_AUDIT_ABANDONED=ignore composer audit

static analysis:
  image: $BUILDIMAGE
  stage: analysis
  needs:
    - composer
  script:
    - ./vendor/bin/phpstan analyse

code style:
  image: $BUILDIMAGE
  stage: analysis
  needs:
    - composer
  script:
    - ./vendor/bin/pint --test
    - npm run lint

build docker:
  image: docker:29.0
  stage: docker
  needs:
    - test
  cache: []
  services:
    - name: docker:29.0-dind
      alias: docker
      command: ["--tls=false"]
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ''
  script:
    - if [ "$CI_COMMIT_REF_NAME" = "master" ]; then TAGNAME="latest"; else TAGNAME="$CI_COMMIT_REF_NAME-latest"; fi
    - if [ $CI_COMMIT_TAG ]; then TAGNAME=$CI_COMMIT_TAG ; fi
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker build -f Dockerfile -t $CI_REGISTRY_IMAGE:$TAGNAME .
    - docker push $CI_REGISTRY_IMAGE:$TAGNAME

deploy docker:
  image: docker:29.0
  stage: deploy
  needs:
    - build docker
  only:
    - tags
  cache: []
  services:
    - name: docker:29.0-dind
      alias: docker
      command: ["--tls=false"]
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ''
  script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - echo $DOCKER_ACCESS_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG pwdsafe/pwdsafe:$CI_COMMIT_TAG
    - docker push pwdsafe/pwdsafe:$CI_COMMIT_TAG
